export const operationalStatuses = [
    { status: "planned", title: "Station approved/proposed" },
    { status: "under construction", title: "Actively being built; not operational" },
    { status: "operational", title: "Built and actively functioning" },
    { status: "decommissioned", title: "Formally closed; operations permanently ceased" },
    { status: "abandoned", title: "Informally or historically deserted" },
]

export const zones_regions = {
    "antarctic-peninsula": [
        "trinity-peninsula",
        "anvers-island",
        "adelaide-island",
        "argentine-islands",
        "alexander-island",
        "graham-land",
        "palmer-land",
        "joinville-island",
        "james-ross-island",
        "south-shetland-islands",
        "south-orkney-islands",
    ],
    "east-antarctica": [
        "weddell-sea",
        "queen-maud-land",
        "enderby-land",
        "mac-robertson-land",
        "princess-elizabeth-land",
        "wilhelm-ii-land",
        "queen-mary-land",
        "wilkes-land",
        "adelie-land",
        "george-v-land",
        "oates-land",
        "east-antarctic-plateau",
        "south-pole",
        "prydz-bay",
        "ingrid-christensen-coast",
        "shackleton-ice-shelf",
    ],
    "west-antarctica": [
        "ross-sea",
        "ross-island",
        "ross-ice-shelf",
        "marie-byrd-land",
        "ellsworth-land",
        "ellsworth-mountains",
        "amundsen-sea",
        "pine-island-bay",
        "thurston-island",
    ],
}